//
//  Copyright (c) 2016 Rich Relevance Inc. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

#import "RCHPlacementsBuilder.h"

/*!
 A request builder for the personalize endpoint. 
 */
NS_ASSUME_NONNULL_BEGIN
@interface RCHPersonalizeBuilder : RCHPlacementsBuilder

///-------------------------------
/// @name Initialization
///-------------------------------

/*!
 *  Create an instance configured with the appropriate path
 *
 *  @return A newly created instance
 */
- (instancetype)init NS_DESIGNATED_INITIALIZER;

///-------------------------------
/// @name Request Parameters
///-------------------------------

/*!
 *  Cart value, expressed in cents (for example, $10 would be represented as 1000). Used for cart-value targeted campaigns.
 *
 *  @param cartValue Cart value in cents
 */
- (instancetype)setCartValue:(NSInteger)cartValue;

/*!
 *  Spoof string generated by RichPreview. See Managing RichPromo Campaigns in the RichRelevance help for details.
 *
 *  @param spoofString A spoof string
 */
- (instancetype)setSpoofString:(NSString *)spoofString;

/*!
 *  Email campaign ID. Can be any alphanumeric string.
 *
 *  @param emailCampaignID An email campaign ID
 */
- (instancetype)setEmailCampaignID:(NSString *)emailCampaignID;

/*!
 *  External category IDs. Used to pass category context information. For the category_page, the expected value is a single external category ID. For other page types, a list of pipe-separated category IDs.
 *
 *  @param externalCategoryIDs An NSArray of NSString instances representing category IDs
 */
- (instancetype)setExternalCategoryIDs:(NSArray<NSString *> *)externalCategoryIDs;

/*!
 *  Set the category name.
 *
 *  @param categoryName A category name
 */
- (instancetype)setCategoryName:(NSString *)categoryName;

/*!
 *  The upper limit on the number of recommendations returned from each strategy.
 *
 *  @param count Count of products to return. Default=5, Max=~ 20
 */
- (instancetype)setRecProductCount:(NSInteger)count;

/*!
 *  Retrieves custom attributes provided in the catalog feed.
 *
 *  @param attributes A list of NSString instances, pass a list containing a single value of * to retrieve all attributes.
 */
- (instancetype)setCatalogFeedCustomAttributes:(NSArray<NSString *> *)attributes;

@end
NS_ASSUME_NONNULL_END
